#!/usr/bin/env groovy

node {
    prepare()

    stage('build-ut') {
        buildUnitTest()
    }
}

def prepare() {
    checkoutGitRepos()
}

def checkoutGitRepos() {
    checkout([
            $class                           : 'GitSCM',
            branches                         : [[name: "refs/heads/master"]],
            doGenerateSubmoduleConfigurations: false,
            extensions                       : [
                    [$class: 'RelativeTargetDirectory', relativeTargetDir: "sample-app"],
            ],
            submoduleCfg                     : [],
            userRemoteConfigs                : [[credentialsId: 'jenkins-github', url: "git@github.com:alacambra/jenkins-pipeline.git"]]
    ])
}

def buildUnitTest() {
    dir("hello-app") {
        def mvnHome = tool name: 'Maven3', type: 'maven'
        sh "${mvnHome}/bin/mvn -B test -DbuildNumber=b1"
    }
    //mvn.cleanPackage("1", 'hello-app')
    unitTestReports()
}

def unitTestReports() {
    junit 'hello-app/target/surefire-reports/**/*.xml'
}