#!/usr/bin/env groovy

pipeline {
    agent any

    environment {
        TEST_SERVER = '34.209.37.159'
    }

    stages {

        stage('print-env'){
            steps{
                sh 'printenv'
            }
        }

        stage('prepare'){
            steps{
                prepare()
            }
        }
    
        stage('build-ut') {
            steps{
                buildUnitTest()
            }
        }

        stage('scp') {
            steps{
                copyToWf()
            }
        }
    }
}

def prepare() {
    checkoutGitRepos()
}

def checkoutGitRepos() {
    checkout([
            $class                           : 'GitSCM',
            branches                         : [[name: "refs/heads/master"]],
            doGenerateSubmoduleConfigurations: false,
            extensions                       : [
                    [$class: 'RelativeTargetDirectory', relativeTargetDir: "code"],
            ],
            submoduleCfg                     : [],
            userRemoteConfigs                : [[credentialsId: 'jenkins-github', url: "git@github.com:alacambra/jenkins-pipeline.git"]]
    ])
}

def buildUnitTest() {
    dir("code/sample-app/hello-app") {
        def mvnHome = tool name: 'Maven3', type: 'maven'
        sh "ls -la /etc/alternatives/java && ${mvnHome}/bin/mvn -B test package -DbuildNumber=b1"
    }
    //mvn.cleanPackage("1", 'hello-app')
    unitTestReports()
}

def copyToWf(){
     withCredentials([sshUserPrivateKey(credentialsId: "aws_pkm15", keyFileVariable: 'keyfile')]) {
        sh "ls -la"
        sh "pwd"
        sh "ls -la code/sample-app/hello-app/target/"
        sh "scp -vi ${keyfile} code/sample-app/hello-app/target/app.war ubuntu@${TEST_SERVER}:/home/ubuntu/wildfly-13.0.0.Final/standalone/deployments"
   }
}

def unitTestReports() {
    junit 'code/sample-app/hello-app/target/surefire-reports/**/*.xml'
}